export interface MenuInfo {
    children: [],
    component: '',
    createBy?: '',
    createTime?: '',
    icon?: '',
    isCache?: ''
    isFrame?: '',
    menuId: number,
    menuName: string,
    menuType?: string,
    orderNum: number,
    parentId?: number,
    parentName: string,
    path: string,
    perms: string,
    query?: string,
    remark?: string,
    status: string,
    updateBy?: string,
    updateTime?: string,
    visible: string,
}
